version: 0.2

env:
  variables:
    CI: "true"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
