version: 0.2

env:
  variables:
    CI: "true"

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - aws s3 cp build s3://www.pageturner.io/ --recursive
artifacts:
  files:
    - "**/*"
  base-directory: build
